name: Publish Package on GitHub

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install Dependencies
      run: npm ci
    
    - name: Create dist folder
      run: npm run build


    - name: Version and publish
      run: |
        git pull
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        npm version patch -m "Bump version to %s [skip ci]"
        git tag v$(node -p "require('./package.json').version")
        git push origin v$(node -p "require('./package.json').version")
        npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}