name: Publish Package on GitHub

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install Dependencies
      run: npm ci
    
    - name: Create dist folder
      run: npm run build

    - name: Authenticate to npm
      run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

    - name: Version and publish
      run: |
        git pull
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        npm version patch -m "Bump version to %s [skip ci]"
        TAG="v$(node -p "require('./package.json').version")"
        # Delete local tag if it exists
        if git rev-parse "$TAG" >/dev/null 2>&1; then
          git tag -d "$TAG"
        fi
        # Delete remote tag if it exists
        if git ls-remote --tags origin | grep -q "refs/tags/$TAG$"; then
          git push --delete origin "$TAG"
        fi
        git tag "$TAG"
        git push origin "$TAG"
        npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}